##The following functions together generate an object that comprises of a matrix and a cache which, when followed by computation of the inverse,stores it.
##The functions provide access to the matrix and the cache through a list of functions that set/retieve them. 

## 'makeCacheMatrix' generates a special "matrix" which can also cache its inverse

makeCacheMatrix <- function(x = matrix()) {                        ## Returns a list of objects of class function that set and retrieve the matrix as well as its inverse. 
                                                                                                ## 'x' is a 1X1 matrix object. 'inverse' is the cache used to store the inverse of x.
        inverse <- matrix(,0,0)      
       
        setMatrix <- function(mat) {                                      ##Sets the matrix 'x' created in the parent environment (the environment of makeCacheMatrix) to 'mat',
                                                                                          #provided that mat is not identical to x.If x is reset,the inverse cache is emptied(set to a 0X0 matrix) as well.
                             if(!identical(x,mat)){                             
                                                             x <<- mat
                                                             inverse <<- matrix(,0,0)
                             }
        }
        
        getMatrix <- function()  {x}                                               ##Retrieves the matrix 'x'                                  
        
        setInverse <- function(inv)  {inverse <<- inv}                  ##Sets the cache to 'inv'(the argument provided to the function)
        
        getInverse <- function() {inverse}                                   ##Retrieves the matrix stored in the cache
        
        list(setMatrix = setMatrix,getMatrix = getMatrix,setInverse = setInverse,getInverse = getInverse)
}


## 'cacheSolve' computes the inverse of the given matrix, provided that the cache(which stores the inverse) is empty



cacheSolve <- function(x,...) {                                                                            ## Returns a matrix that is the inverse of the matrix that can be retreived though 'x'
                                                                                                                             ## 'x' is the list generated by makeCacheMatrix()
                inverse <- x$getInverse()
       
               if(length(inverse) == 0){                                                                      ##When matrix is reset,the cache is set to a 0X0 matrix whose length is 0.
                                                      inverse <- solve(x$getMatrix())                   #The condition provided is satisfied only when the inverse cache is empty.
                                                      x$setInverse(inverse)
               }
              
              inverse                                                                                              
}
